<?php

namespace StolarzBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EdgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdgeRepository extends EntityRepository
{
}
